# Generated by Django 5.0.6 on 2024-10-29 12:03

import django.core.validators
import nazer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(max_length=250)),
                ('channel', models.IntegerField(blank=True, default=1, null=True)),
                ('time', models.DateTimeField()),
                ('device_name', models.CharField(max_length=250)),
                ('alarm_name', models.CharField(max_length=250)),
                ('ip', models.GenericIPAddressField()),
                ('file', models.FileField(blank=True, null=True, upload_to=nazer.models.hashed_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('original_file_name', models.TextField(blank=True, null=True)),
                ('is_sms_sent', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('handled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Alarm_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm_SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.CharField(default='-', max_length=250, null=True)),
            ],
        ),
    ]
