# Generated by Django 5.0.4 on 2024-08-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loggerapp', '0003_delete_logentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generallog',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='speicallog',
            options={'ordering': ['-time']},
        ),
    ]
